// web/angular/src/app/app.component.ts
import {Component, ViewChild} from '@angular/core';
// @ts-ignore
import Lodash from 'lodash';
import Axios from 'axios'
// @ts-ignore
import Qs from 'qs'
import {ClickService, RotateService, SlideRegionService, SlideService} from "./app.service";
import {ClickRef} from "go-captcha-angular";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor(
    private clickService: ClickService,
    private slideService: SlideService,
    private slideRegionService: SlideRegionService,
    private rotateService: RotateService,
  ) {}

  ngAfterViewInit() {
    this.requestClickData()
    this.requestSlideData()
    this.requestSlideRegionData()
    this.requestRotateData()
  }

  ////////////////////////////////////
  clickData = {
    image: '',
    thumb: '',
  }

  clickConfig = {
    width: 300,
    height: 220,
  }

  clickEvents = {
    click: (x: number, y: number): void => {
      console.log("click >>>>>>>", x, y)
    },
    confirm: (dot: any, reset: Function) => {
      this.confirmClickEvent(dot, reset)
    },
    refresh: () => {
      this.requestClickData()
    },
    close: (): void => {
      console.log("close >>>>>>>")
    }
  }

  @ViewChild('clickRef') clickRef: ClickRef | any;

  confirmClickEvent(dot: any, reset: Function) {
    this.clickService.confirmData(dot, () => {
      setTimeout(() => {
        this.requestClickData()
      }, 1000)
    })
  }

  requestClickData(){
    this.clickRef.clear && this.clickRef.clear()
    this.clickService.requestData((res) => {
      this.clickData.image = res.image
      this.clickData.thumb = res.thumb
    })
  }

  /////////////////////////////////////////

  slideData = {
    thumbX: 20,
    thumbY: 20,
    thumbWidth: 0,
    thumbHeight: 0,
    image: '',
    thumb: '',
  }

  slideConfig = {
    width: 300,
    height: 220,
  }

  slideEvents = {
    move: (x: number, y: number): void => {
      console.log("move >>>>>>>", x, y)
    },
    confirm: (point: any, reset: Function) => {
      this.confirmSlideEvent(point, reset)
    },
    refresh: () => {
      this.requestSlideData()
    },
    close: (): void => {
      console.log("close >>>>>>>")
    }
  }

  @ViewChild('slideRef') slideRef: any;

  confirmSlideEvent(point: any, reset: Function) {
    this.slideService.confirmData(point, () => {
      setTimeout(() => {
        this.requestSlideData()
      }, 1000)
    })
  }

  requestSlideData(){
    this.slideRef.clear && this.slideRef.clear()
    this.slideService.requestData((res) => {
      this.slideData.thumbX = res.thumbX
      this.slideData.thumbY = res.thumbY
      this.slideData.thumbWidth = res.thumbWidth
      this.slideData.thumbHeight = res.thumbHeight
      this.slideData.image = res.image
      this.slideData.thumb = res.thumb

      // this.slideData = {
      //   image: res.image,
      //   thumb: res.thumb,
      //   thumbX: res.thumbX,
      //   thumbY: res.thumbY,
      //   thumbWidth: res.thumbWidth,
      //   thumbHeight: res.thumbHeight,
      // }
    })
  }

  ////////////////////////////////

  slideRegionData = {
    thumbX: 20,
    thumbY: 20,
    thumbWidth: 80,
    thumbHeight: 80,
    image: '',
    thumb: '',
  }
  slideRegionEvents = {
    move: (x: number, y: number): void => {
      console.log("move >>>>>>>", x, y)
    },
    confirm: (point: any, reset: Function) => {
      this.confirmSlideRegionEvent(point, reset)
    },
    refresh: () => {
      this.requestSlideRegionData()
    },
    close: (): void => {
      console.log("close >>>>>>>")
    }
  }

  slideRegionConfig = {
    width: 300,
    height: 220,
  }

  @ViewChild('slideRegionRef') slideRegionRef: any;

  confirmSlideRegionEvent(point: any, reset: Function) {
    this.slideRegionService.confirmData(point, () => {
      setTimeout(() => {
        this.requestSlideRegionData()
      }, 1000)
    })
  }

  requestSlideRegionData(){
    this.slideRegionRef.clear && this.slideRegionRef.clear()
    this.slideRegionService.requestData((res) => {
      this.slideRegionData.thumbX = res.thumbX
      this.slideRegionData.thumbY = res.thumbY
      this.slideRegionData.thumbWidth = res.thumbWidth
      this.slideRegionData.thumbHeight = res.thumbHeight
      this.slideRegionData.image = res.image
      this.slideRegionData.thumb = res.thumb
    })
  }

  ////////////////////////////////
  rotateData = {
    angle: 20,
    image: '',
    thumb: '',
  }

  rotateEvents = {
    rotate: (angle: number): void => {
      console.log("rotate >>>>>>>", angle)
    },
    confirm: (dot: any, reset: Function) => {
      this.confirmRotateEvent(dot, reset)
    },
    refresh: () => {
      this.requestRotateData()
    },
    close: (): void => {
      console.log("close >>>>>>>")
    }
  }

  rotateConfig = {
    width: 300,
    height: 220,
  }

  @ViewChild('rotateRef') rotateRef: any;

  confirmRotateEvent(dot: any, reset: Function) {
    this.rotateService.confirmData(dot, () => {
      setTimeout(() => {
        this.requestRotateData()
      }, 1000)
    })
  }

  requestRotateData(){
    this.rotateRef.clear && this.rotateRef.clear()
    this.rotateService.requestData((res) => {
      this.rotateData.angle = res.angle || 0
      this.rotateData.image = res.image
      this.rotateData.thumb = res.thumb
    })
  }

  handleEvent() {
    console.log(">>>>>> click")
  }
}

<div class="example" style="padding-top: 40px">
  <go-captcha-click
    [data]="clickData"
    [events]="clickEvents"
    [config]="clickConfig"
    #clickRef
  ></go-captcha-click>
  <br/>
  <go-captcha-slide
    [data]="slideData"
    [events]="slideEvents"
    [config]="slideConfig"
    #slideRef
  ></go-captcha-slide>
  <br/>
  <go-captcha-slide-region
    [data]="slideRegionData"
    [events]="slideRegionEvents"
    [config]="slideRegionConfig"
    #slideRegionRef
  ></go-captcha-slide-region>
  <br/>
  <go-captcha-rotate
    [data]="rotateData"
    [events]="rotateEvents"
    [config]="rotateConfig"
    #rotateRef
  ></go-captcha-rotate>
  <br/>
  <go-captcha-button [clickEvent]="handleEvent"></go-captcha-button>
</div>

// web/svelte/src/App.svelte
<script>
	import {Click, Rotate, Slide, SlideRegion, Button} from "go-captcha-svelte";
	// Cache Testing
  // import {Click, Rotate, Slide, SlideRegion, Button} from "./cache/dist/index.js";
  import {useClickHandler} from "./hooks/useClickHandler.js";
  import {useSlideHandler} from "./hooks/useSlideHandler.js";
  import {useRotateHandler} from "./hooks/useRotateHandler.js";
  import {onMount} from "svelte";
  import {get} from 'svelte/store';
  import {Toaster} from 'svelte-french-toast'

	let type = "default"

  let clickRef;
  const clickHandler = useClickHandler({
    getApi: "/api/go-captcha-data/click-basic",
    checkApi: "/api/go-captcha-check-data/click-basic",
  })
  let clickData = get(clickHandler.data)
  clickHandler.data.subscribe(value => {
    clickData = value
  });

  let slideRef;
  const slideHandler = useSlideHandler({
    getApi: "/api/go-captcha-data/slide-basic",
    checkApi: "/api/go-captcha-check-data/slide-basic",
  })
  let slideData = get(slideHandler.data)
  slideHandler.data.subscribe(value => {
    slideData = value
  });

  let slideRegionRef;
  const slideRegionHandler = useSlideHandler({
    getApi: "/api/go-captcha-data/slide-region",
    checkApi: "/api/go-captcha-check-data/slide-region"
  })
  let slideRegionData = get(slideRegionHandler.data)
  slideRegionHandler.data.subscribe(value => {
    slideRegionData = value
  });

  let rotateRef;
  const rotateHandler = useRotateHandler({
    getApi: "/api/go-captcha-data/rotate-basic",
    checkApi: "/api/go-captcha-check-data/rotate-basic",
  })
  let rotateData = get(rotateHandler.data)
  rotateHandler.data.subscribe(value => {
    rotateData = value
  });

  onMount(() => {
    clickHandler.init(clickRef)
    slideHandler.init(slideRef)
    slideRegionHandler.init(slideRegionRef)
    rotateHandler.init(rotateRef)
  })

  const clickEvents = {
    click(x, y) {
      console.log("click >>>>>>>", x, y)
    },
    confirm(dots, reset) {
      console.log("dots >>>>>>>", dots)
      clickHandler.confirmEvent(dots)
    },
    refresh() {
      console.log("refresh >>>>>>>")
      clickHandler.refreshEvent()
      // clickRef.clear && clickRef.clear()
    },
    close() {
      console.log("close >>>>>>>")
    }
	}


	const slideEvents = {
    move(x, y) {
      console.log("move >>>>>>>", x, y)
    },
    confirm(point, reset) {
      console.log("point >>>>>>>", point)

      slideHandler.confirmEvent(point)
    },
    refresh() {
      console.log("refresh >>>>>>>")
      slideHandler.refreshEvent()
      // slideRef.clear && slideRef.clear()
    },
    close() {
      console.log("close >>>>>>>")
    }
	}

	const slideRegionEvents = {
    move(x, y) {
      console.log("move >>>>>>>", x, y)
    },
    confirm(point, reset) {
      console.log("point >>>>>>>", point)
      slideRegionHandler.confirmEvent(point)
    },
    refresh() {
      console.log("refresh >>>>>>>")
      // slideRegionRef.clear && slideRegionRef.clear()
      slideRegionHandler.refreshEvent()
    },
    close() {
      console.log("close >>>>>>>")
    }
	}

	const rotateEvents = {
    rotate(angle) {
      console.log("rotate >>>>>>>", angle)
    },
    refresh() {
      console.log("refresh >>>>>>>")
      // rotateRef.clear && rotateRef.clear()
      rotateHandler.refreshEvent()
    },
    confirm(point, reset) {
      console.log("point >>>>>>>", point)

      setTimeout(() => {
        reset()
      }, 2000)
      rotateHandler.confirmEvent(point)
    },
    close() {
      console.log("close >>>>>>>")
    }
	}
</script>

<div class="container">
  <Toaster />
  <br/>
  <br/>

  <Click data={clickData} events={clickEvents} bind:this={clickRef}/>
  <br/>

  <Slide data={slideData} events={slideEvents} bind:this={slideRef}/>
  <br />

  <SlideRegion data={slideRegionData} events={slideRegionEvents} bind:this={slideRegionRef}/>
  <br />

  <Rotate data={rotateData} events={rotateEvents} bind:this={rotateRef}/>
  <br />

  <Button clickEvent={() => type="warn"} type={type}/>

</div>


<style lang="css">
.container{
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding-top: 40px;
  padding-bottom: 40px;
}

</style>
