// web/react/src/components/ClickTextCapt.js
import React, {useRef} from 'react'
import GoCaptcha from 'go-captcha-react'
// Cache Testing
// import GoCaptcha from '../cache'
import {useClickHandler} from "../hooks/useClickHandler";

function ClickTextCapt() {
  const domRef = useRef(null)

  const handler = useClickHandler(domRef, {
    getApi: "/api/go-captcha-data/click-basic",
    checkApi: "/api/go-captcha-check-data/click-basic"
  })

  return (
    <GoCaptcha.Click
      config={{
        width: 300,
        height: 220,
        dotSize: 24,
      }}
      data={handler.data}
      events={{
        close: handler.closeEvent,
        refresh: handler.refreshEvent,
        confirm: handler.confirmEvent,
      }}
      ref={domRef}
    />
  );
}

export default ClickTextCapt;

// web/vue/src/components/click-text-capt.vue
<template>
  <gocaptcha-click
    :data="handler.data"
    :events="{
      click: clickevnt,
      close: handler.closeEvent,
      refresh: handler.refreshEvent,
      confirm: handler.confirmEvent,
    }"
  />
</template>

<script setup>
import {useHandler} from "../hooks/useClickHandler";
const handler = useHandler({
  getApi: "/api/go-captcha-data/click-basic",
  checkApi: "/api/go-captcha-check-data/click-basic"
})

const clickevnt = (x, y) => {
  console.log('click >>>>>>>>>>>', x, y)
}
</script>

<style>

</style>
